# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2ddacd21b77441ec7ff501f5bbca11623d9e86e4e6e0076a12a9ae12539f6e1945719e6117ba58c58339da937aa290f395df8e1ac1dec7d6d3a056c76940185

test:
  secret_key_base: 44e7fc9043ca74fd98853cb1e3aca3552b36fab1e101b837bfa1989b5f5d1eeb1af41d7d8f868a37d997b40c015b2a6e78a7a0bc819f0de8c30280dd891f173b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 96abc0f257ce7eb15ba2db0ebccdd3209ae986d57f7c46db08a9f8630f4057ff2c94cc8004bfc80cf0f8b463102fe475381e723aff167f0e14f0c6bfe276fba4
